### ISSUE TITLE
Inspection.capx

### ISSUE THREAD

**Issue by djjterror** [FrenchYann/JSON_for_construct2#5] opened 2018-01-25 15:50 UTC
File opens ok, 
first two calls (findFriends and printFriends) work ok but the third one (lookInside) get's following error:

Javascript error!
Unable to get property "apply" of undefined or null reference expressions.js, line 347 (col 3)

C2 v250 64bit, win 10 home 64bit.

**Comment by FrenchYann** [comment] 2018-02-07 19:34
Duplicate of #4

**Closed as completed by FrenchYann** 2018-02-07 19:34 UTC
